data = [
    {'name': 'Cristiano Ronaldo', 'follower_count': 620, 'profession': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 500, 'profession': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 430, 'profession': 'Singer / Actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 420, 'profession': 'Entrepreneur / Model', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 390, 'profession': 'Actor', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 380, 'profession': 'Singer', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 360, 'profession': 'Entrepreneur / TV Personality', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 260, 'profession': 'Cricketer', 'country': 'India'},
    {'name': 'Beyoncé', 'follower_count': 300, 'profession': 'Singer', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 340, 'profession': 'Singer / Songwriter', 'country': 'United States'},

    {'name': 'Zendaya', 'follower_count': 200, 'profession': 'Actress', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 290, 'profession': 'Singer', 'country': 'Canada'},
    {'name': 'Khabane Lame', 'follower_count': 160, 'profession': 'Content Creator', 'country': 'Italy'},
    {'name': 'Shakira', 'follower_count': 140, 'profession': 'Singer', 'country': 'Colombia'},
    {'name': 'Billie Eilish', 'follower_count': 120, 'profession': 'Singer', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 150, 'profession': 'Singer / Entrepreneur', 'country': 'Barbados'},
    {'name': 'Neymar Jr.', 'follower_count': 215, 'profession': 'Footballer', 'country': 'Brazil'},
    {'name': 'LeBron James', 'follower_count': 160, 'profession': 'Basketball Player', 'country': 'United States'},
    {'name': 'Eminem', 'follower_count': 110, 'profession': 'Rapper', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 85, 'profession': 'Footballer / Model', 'country': 'United Kingdom'},

    {'name': 'Kendall Jenner', 'follower_count': 280, 'profession': 'Model', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 250, 'profession': 'Singer / Actress', 'country': 'United States'},
    {'name': 'Gigi Hadid', 'follower_count': 90, 'profession': 'Model', 'country': 'United States'},
    {'name': 'Hailey Bieber', 'follower_count': 60, 'profession': 'Model', 'country': 'United States'},
    {'name': 'Chris Hemsworth', 'follower_count': 60, 'profession': 'Actor', 'country': 'Australia'},
    {'name': 'Tom Holland', 'follower_count': 70, 'profession': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Robert Downey Jr.', 'follower_count': 55, 'profession': 'Actor', 'country': 'United States'},
    {'name': 'Will Smith', 'follower_count': 75, 'profession': 'Actor', 'country': 'United States'},
    {'name': 'Scarlett Johansson', 'follower_count': 50, 'profession': 'Actress', 'country': 'United States'},
    {'name': 'Gal Gadot', 'follower_count': 95, 'profession': 'Actress', 'country': 'Israel'},

    {'name': 'Elon Musk', 'follower_count': 70, 'profession': 'Entrepreneur', 'country': 'South Africa'},
    {'name': 'Jeff Bezos', 'follower_count': 40, 'profession': 'Entrepreneur', 'country': 'United States'},
    {'name': 'Mark Zuckerberg', 'follower_count': 20, 'profession': 'Entrepreneur', 'country': 'United States'},
    {'name': 'Sundar Pichai', 'follower_count': 12, 'profession': 'Tech CEO', 'country': 'India'},
    {'name': 'Satya Nadella', 'follower_count': 10, 'profession': 'Tech CEO', 'country': 'India'},
    {'name': 'Tim Cook', 'follower_count': 15, 'profession': 'Tech CEO', 'country': 'United States'},
    {'name': 'MrBeast', 'follower_count': 200, 'profession': 'YouTuber', 'country': 'United States'},
    {'name': 'PewDiePie', 'follower_count': 30, 'profession': 'YouTuber', 'country': 'Sweden'},
    {'name': 'Ninja', 'follower_count': 25, 'profession': 'Streamer', 'country': 'United States'},
    {'name': 'Pokimane', 'follower_count': 15, 'profession': 'Streamer', 'country': 'Canada'},

    {'name': 'Novak Djokovic', 'follower_count': 13, 'profession': 'Tennis Player', 'country': 'Serbia'},
    {'name': 'Roger Federer', 'follower_count': 12, 'profession': 'Tennis Player', 'country': 'Switzerland'},
    {'name': 'Lewis Hamilton', 'follower_count': 34, 'profession': 'F1 Driver', 'country': 'United Kingdom'},
    {'name': 'Max Verstappen', 'follower_count': 18, 'profession': 'F1 Driver', 'country': 'Netherlands'},
    {'name': 'Conor McGregor', 'follower_count': 47, 'profession': 'MMA Fighter', 'country': 'Ireland'},
    {'name': 'Kylian Mbappé', 'follower_count': 120, 'profession': 'Footballer', 'country': 'France'},
    {'name': 'Zlatan Ibrahimović', 'follower_count': 60, 'profession': 'Footballer', 'country': 'Sweden'},
    {'name': 'Megan Rapinoe', 'follower_count': 3, 'profession': 'Footballer', 'country': 'United States'},
    {'name': 'Simone Biles', 'follower_count': 8, 'profession': 'Gymnast', 'country': 'United States'},
    {'name': 'Naomi Osaka', 'follower_count': 6, 'profession': 'Tennis Player', 'country': 'Japan'},

    {'name': 'Gordon Ramsay', 'follower_count': 20, 'profession': 'Chef', 'country': 'United Kingdom'},
    {'name': 'Salt Bae', 'follower_count': 52, 'profession': 'Chef / Internet Personality', 'country': 'Turkey'},
    {'name': 'Jamie Oliver', 'follower_count': 10, 'profession': 'Chef', 'country': 'United Kingdom'},
    {'name': 'Heston Blumenthal', 'follower_count': 2, 'profession': 'Chef', 'country': 'United Kingdom'},
    {'name': 'Massimo Bottura', 'follower_count': 1, 'profession': 'Chef', 'country': 'Italy'},
    {'name': 'Gigi D’Agostino', 'follower_count': 1, 'profession': 'DJ', 'country': 'Italy'},
    {'name': 'David Guetta', 'follower_count': 20, 'profession': 'DJ / Producer', 'country': 'France'},
    {'name': 'Calvin Harris', 'follower_count': 15, 'profession': 'DJ / Producer', 'country': 'United Kingdom'},
    {'name': 'Martin Garrix', 'follower_count': 16, 'profession': 'DJ / Producer', 'country': 'Netherlands'},
    {'name': 'Armin van Buuren', 'follower_count': 10, 'profession': 'DJ / Producer', 'country': 'Netherlands'},

    {'name': 'Emma Watson', 'follower_count': 75, 'profession': 'Actress', 'country': 'United Kingdom'},
    {'name': 'Natalie Portman', 'follower_count': 9, 'profession': 'Actress', 'country': 'United States'},
    {'name': 'Brie Larson', 'follower_count': 8, 'profession': 'Actress', 'country': 'United States'},
    {'name': 'Millie Bobby Brown', 'follower_count': 65, 'profession': 'Actress', 'country': 'United Kingdom'},
    {'name': 'Pedro Pascal', 'follower_count': 12, 'profession': 'Actor', 'country': 'Chile'},
    {'name': 'Keanu Reeves', 'follower_count': 6, 'profession': 'Actor', 'country': 'Canada'},
    {'name': 'Morgan Freeman', 'follower_count': 4, 'profession': 'Actor', 'country': 'United States'},
    {'name': 'Cillian Murphy', 'follower_count': 2, 'profession': 'Actor', 'country': 'Ireland'},
    {'name': 'Henry Cavill', 'follower_count': 25, 'profession': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Jason Momoa', 'follower_count': 18, 'profession': 'Actor', 'country': 'United States'},

    {'name': 'Oprah Winfrey', 'follower_count': 22, 'profession': 'TV Host', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 60, 'profession': 'TV Host', 'country': 'United States'},
    {'name': 'Trevor Noah', 'follower_count': 10, 'profession': 'Comedian', 'country': 'South Africa'},
    {'name': 'Jimmy Fallon', 'follower_count': 25, 'profession': 'TV Host', 'country': 'United States'},
    {'name': 'James Corden', 'follower_count': 7, 'profession': 'TV Host', 'country': 'United Kingdom'},
    {'name': 'Stephen King', 'follower_count': 6, 'profession': 'Writer', 'country': 'United States'},
    {'name': 'J.K. Rowling', 'follower_count': 9, 'profession': 'Writer', 'country': 'United Kingdom'},
    {'name': 'George R.R. Martin', 'follower_count': 5, 'profession': 'Writer', 'country': 'United States'},
    {'name': 'Neil Gaiman', 'follower_count': 3, 'profession': 'Writer', 'country': 'United Kingdom'},
    {'name': 'Paulo Coelho', 'follower_count': 4, 'profession': 'Writer', 'country': 'Brazil'}
]



